// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectorys():Promise<Array<string>>;

export function OpenInVsCode(arg1:string):Promise<void>;
