// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectorys() {
  return window['go']['main']['App']['GetDirectorys']();
}

export function OpenInVsCode(arg1) {
  return window['go']['main']['App']['OpenInVsCode'](arg1);
}
